### ISSUE TITLE
nmap -sn : no match found

### ISSUE THREAD

**Issue by Pavivenkatesan** [treehouses/treehouses.github.io#669] opened 2020-07-15 23:40 UTC
### Problem
Under Step 1 inside the link "**Finding Pi**", steps mentioned under "**Method 3: nmap command**" displays "**no match found**"
 ### Steps to reproduce the problem

1. Navigate to the link, https://treehouses.io/#!./pages/vi/find-pi.md
2. Scroll down to **"Method 3: nmap command"**
3. Follow the installation steps for nmap using brew.
4. Find your computer's IP address
4. Type the command **nmap -sn 192.168.1.***(notation for whole subnet range of all your devices' IPs)

 ### Screenshots
![image](https://user-images.githubusercontent.com/37712975/87610154-8c72ff80-c6d2-11ea-95ae-b603cff8b5df.png)

 ### Proposed solution
This is my first time using nmap so I would appreciate any solutions

**Comment by leosp123** [comment] 2020-07-24 02:44
I can try to see if I get the same issue on Windows. Maybe try connecting to another network?

**Comment by SeanTang001** [comment] 2020-09-22 05:01
Are you sure your network uses the subnet range "192.168.1.\*"? It could be "192.168.0.\*" instead.   
Type "ipconfig" to check your own subnet range.

**Comment by SeanTang001** [comment] 2020-09-22 05:04
@dogi please close; the issue is already resolved in https://treehouses.io/#!./pages/vi/find-pi.md

**Closed as completed** 2020-11-24 04:42 UTC
